name: ci
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 4 * * *'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: go test -v ./...
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*integration test* ${{ matrix.go-version }} on ${{ matrix.platform }}'
        url: ${{ secrets.SLACK_WEBHOOK }}
        mention_if: 'failure'
